# Generated by Django 5.1.7 on 2025-04-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nomnbre',
            new_name='nombre',
        ),
    ]
