# Generated by Django 5.1.7 on 2025-04-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_nomnbre_categoria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
